export const DETAILS_LOADING = 'DETAILS_LOADING'
export const DETAILS_LOADING_SUCCESS = 'DETAILS_LOADING_SUCCESS'
export const DETAILS_LOADING_FAILURE = 'DETAILS_LOADING_FAILURE'
export const GALLERY_LOADING = 'GALLERY_LOADING'
export const GALLERY_LOADING_SUCCESS = 'GALLERY_LOADING_SUCCESS'
export const GALLERY_LOADING_FAILURE = 'GALLERY_LOADING_FAILURE'


